/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        script: ['"Caveat"', '"Brush Script MT"', 'cursive'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-badge': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-hero': ['52px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'gutter-mobile': '0.75rem',
      },
      colors: {
        // Material 3 & Inveon token set
        outline: '#727687',
        'on-primary-container': '#f8f7ff',
        'surface-bright': '#f8f9ff',
        'secondary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b3c5ff',
        'outline-variant': '#c2c6d8',
        'on-background': '#0b1c30',
        'primary-fixed': '#dae1ff',
        background: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-high': '#dce9ff',
        'on-error': '#ffffff',
        'secondary-container': '#d8deff',
        tertiary: '#006645',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-fixed-variant': '#3e4660',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'secondary-fixed-dim': '#bec5e5',
        'on-primary-fixed-variant': '#003fa4',
        'on-tertiary-fixed': '#002113',
        'on-primary': '#ffffff',
        'inverse-primary': '#b3c5ff',
        'surface-variant': '#d3e4fe',
        error: '#ba1a1a',
        primary: '#0050cb',
        'on-surface': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary': '#ffffff',
        'surface-tint': '#0054d6',
        secondary: '#565d79',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-container': '#008259',
        'error-container': '#ffdad6',
        'on-surface-variant': '#424656',
        'on-tertiary-fixed-variant': '#005236',
        'inverse-surface': '#213145',
        'primary-container': '#0066ff',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed': '#131a33',
        'on-primary-fixed': '#001849',
        'on-tertiary-container': '#e1ffec',
        'on-secondary-container': '#5a627e',

        // Brand scale
        brand: {
          50: '#eef6ff',
          100: '#d9eaff',
          200: '#bcd9ff',
          300: '#8ec1ff',
          400: '#589eff',
          500: '#2f7bff',
          600: '#0b63f8',
          700: '#084ed2',
          800: '#0c40a9',
          900: '#103984',
        },
        darkNavy: '#070f21',
        footerNavy: '#081226',
        // Organizer back-office sidebar palette (from the organizer UI mockups).
        navy: {
          900: '#071228',
          850: '#0a1936',
          800: '#0f2347',
          700: '#1e3a6d',
        },
        accent: {
          amber: '#f59e0b',
        },
        surface: {
          DEFAULT: '#f8f9ff',
          card: '#ffffff',
          sunken: '#eef2fb',
          raised: '#e5eeff',
        },
        ink: {
          DEFAULT: '#0b1c30', // headings
          body: '#334155', // body text
          muted: '#64748b', // secondary/meta text
          outline: '#727687', // borders, placeholder icons
        },
        success: {
          50: '#f0fdf4',
          500: '#16a34a',
          600: '#15803d',
        },
        warning: {
          50: '#fffbeb',
          500: '#f59e0b',
          600: '#d97706',
        },
        danger: {
          50: '#fef2f2',
          500: '#ef4444',
          600: '#dc2626',
        },
      },
      boxShadow: {
        card: '0 1px 3px rgba(11, 28, 48, 0.06), 0 1px 2px rgba(11, 28, 48, 0.04)',
      },
    },
  },
  plugins: [],
};
